/**
 * Auto-Generated Step Definitions for: Hyundai Calculator - Verify Drive Away pricing for all models and variants
 * Source: calculator_pricing.feature
 * Generated: 2026-09-22T03:58:31.292Z
 * Target URL: https://www.hyundai.com/au/en
 *
 * DOM Field Map:
 *   (no DOM map available — using autoHeal fallbacks)
 *
 * These steps were auto-generated by the Confluence Test Agent because no
 * matching step definitions were found. Each step uses Playwright for real
 * browser interactions and assertions.
 */
import { Given, When, Then } from '@cucumber/cucumber';
import { strict as assert } from 'node:assert';

Given('flag any variant whose Drive Away widget displays {string} or whose CPC page fails to load', async function (param) {
  const inputs = this.page.locator('input:visible');
  const count = await inputs.count();
  let accessibleCount = 0;
  for (let i = 0; i < Math.min(count, 10); i++) {
    const input = inputs.nth(i);
    const id = await input.getAttribute('id').catch(() => null);
    const ariaLabel = await input.getAttribute('aria-label').catch(() => null);
    const placeholder = await input.getAttribute('placeholder').catch(() => null);
    if (id || ariaLabel || placeholder) accessibleCount++;
  }
  assert.ok(accessibleCount > 0 || count === 0, 'Labels should be associated with inputs');
});
