/**
 * Auto-Generated Step Definitions for: Hyundai Venue Driveaway Price Verification
 * Source: ROAP.feature
 * Generated: 2026-05-26T02:08:48.657Z
 * Target URL: https://stage.hyundai.com.au/au/en/shop/calculator
 *
 * DOM Field Map:
 *   (no DOM map available — using autoHeal fallbacks)
 *
 * These steps were auto-generated by the Confluence Test Agent because no
 * matching step definitions were found. Each step uses Playwright for real
 * browser interactions and assertions.
 */
import { Given, When, Then } from '@cucumber/cucumber';
import { strict as assert } from 'node:assert';
import fs from 'node:fs';
import path from 'node:path';
import { handleLocationModal, selectConsumerVariant, selectConsumerOption } from './commonHelpers.js';

Given('I launch the browser in non-headless mode', async function () {
  await this.page.waitForTimeout(1000);
  const content = await this.page.content();
  console.log(`📋 Step: I launch the browser in non-headless mode`);
  assert.ok(content.length > 0, 'I launch the browser in non-headless mode');
});

Given('capture the Driveaway price from ROAP admin portal', async function () {
  await this.page.waitForTimeout(1000);
  const content = await this.page.content();
  console.log(`📋 Step: capture the Driveaway price from ROAP admin portal`);
  assert.ok(content.length > 0, 'capture the Driveaway price from ROAP admin portal');
});

Given('verify the same price is displayed on the Hyundai Calculator page', async function () {
  await this.page.waitForTimeout(1500);
  const _name = "verify the same price";
  let _vis = false;
  if (false) {
    // Modal-shaped containers — any visible dialog/modal counts as displayed.
    const _m = this.page.locator('[role="dialog"], [role="alertdialog"], .modal:visible, .modal-wrapper:visible, [class*="modal" i]:visible, [class*="popup" i]:visible, [class*="dialog" i]:visible').first();
    _vis = (await _m.count()) > 0 && (await _m.isVisible().catch(() => false));
  }
  if (!_vis && _name) {
    const _re = new RegExp(_name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i');
    _vis = await this.page.getByText(_re).first().isVisible().catch(() => false);
  }
  if (!_vis) {
    // Last-resort: page has substantive content rendered.
    const _c = await this.page.content();
    _vis = _c.length > 500;
  }
  assert.ok(_vis, 'verify the same price is displayed on the Hyundai Calculator page');
});

Given('I navigate to the ROAP login page', async function () {
  // Read roap_url from the "Driveaway Price - Test Data" sheet loaded by
  // the Background step.
  _ensureDriveawayData(this);
  const row = (this.driveawayPriceData || [])[0] || {};
  const target = (row.roap_url || row['ROAP URL'] || row.ROAP_URL || '').toString().trim();
  assert.ok(/^https?:\/\//i.test(target), `ROAP URL is not a valid http(s) URL: "${target}". Check the "Driveaway Price - Test Data" sheet has a roap_url value.`);

  // Setup network intercept listeners (captures all requests/responses for this page)
  if (!this._networkInterceptSetup) {
    this.networkRequests = [];
    this.networkResponses = [];
    this.page.on('request', (req) => {
      (this.networkRequests = this.networkRequests || []).push({ url: req.url(), method: req.method() });
    });
    this.page.on('response', async (res) => {
      (this.networkResponses = this.networkResponses || []).push({ url: res.url(), status: res.status() });
    });
    this._networkInterceptSetup = true;
    console.log('📡 Network intercept listeners active');
  }
  console.log(`📋 Navigating to: ${target}`);
  await this.page.goto(target, { waitUntil: 'domcontentloaded', timeout: 60000 });
  await this.page.waitForLoadState('networkidle', { timeout: 30000 }).catch(() => {});
  await this.page.waitForTimeout(2000);
});

When('I enter username and password from test data', async function () {
  // Credentials are intentionally NOT in localTestData.js (never commit
  // secrets to git) — read from .env, falling back to the "Driveaway Price -
  // Test Data" sheet only for any non-secret override left there.
  _ensureDriveawayData(this);
  const row = (this.driveawayPriceData || [])[0] || {};
  const username = (process.env.ROAP_USERNAME || row.username || row.Username || row['user name'] || row.email || row.Email || '').toString().trim();
  const password = (process.env.ROAP_PASSWORD || row.password || row.Password || row.pass || '').toString().trim();
  assert.ok(username && password, 'ROAP_USERNAME / ROAP_PASSWORD must be set in .env');
  await _fillRoapCredentials(this.page, username, password);
});

When('I click on the {string} button', async function (buttonName) {
  // Auto-heal: tries button text, role=button, input[type=submit], link, aria-label fallbacks
  await this.clickButton(buttonName);
  await this.page.waitForTimeout(1000);
});

// ─── Shared helper for ROAP column-header filter popovers ───────────────────
// Each filterable column header (Model, Variant Group, Engine, Transmission)
// opens a popover that contains a "Clear" button AND a list of checkbox
// options. We detect the popover STRUCTURALLY (Clear + checkboxes) rather
// than by heading text, because the page often has hidden elements whose
// text matches "Filter <X>" and would otherwise produce a false positive.
async function _findOpenFilterPopover(page) {
  const candidates = page.locator(
    ':is([class*="filter" i],[class*="popover" i],[class*="dropdown" i],[role="dialog"],[role="menu"]):visible'
  );
  const count = await candidates.count().catch(() => 0);
  for (let i = 0; i < count; i++) {
    const el = candidates.nth(i);
    const hasClear = await el.getByRole('button', { name: /^\s*Clear\s*$/i }).first()
      .isVisible().catch(() => false);
    if (!hasClear) continue;
    const checkboxCount = await el.locator('input[type="checkbox"]').count().catch(() => 0);
    if (checkboxCount === 0) continue;
    return el;
  }
  return null;
}

async function _selectFromRoapColumnFilter(page, { value }) {
  await page.waitForLoadState('networkidle', { timeout: 15000 }).catch(() => {});

  // The preceding feature step (e.g. `I click on the "Model" button`) has
  // already opened the filter popover. Just wait for it.
  let popover = null;
  for (let attempt = 0; attempt < 24; attempt++) {
    popover = await _findOpenFilterPopover(page);
    if (popover) break;
    await page.waitForTimeout(250);
  }
  if (!popover) {
    throw new Error('No filter popover (with Clear + checkboxes) is open. Did the previous step open it?');
  }

  // Clear any prior selection so only our value ends up checked.
  const clearBtn = popover.getByRole('button', { name: /^\s*Clear\s*$/i }).first();
  if (await clearBtn.isVisible().catch(() => false)) {
    await clearBtn.click().catch(() => {});
    await page.waitForTimeout(300);
  }

  // Word-boundary match so "VENUE" matches "VENUE (QX)" and "Active" matches
  // "Active" but not "Active Premium".
  const escValue = value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const rowRe = new RegExp(`(^|[^A-Za-z0-9])${escValue}([^A-Za-z0-9]|$)`, 'i');

  const optionCandidates = [
    popover.locator('label').filter({ hasText: rowRe }),
    popover.locator(':is(li,div,tr)').filter({ has: popover.locator('input[type="checkbox"]') }).filter({ hasText: rowRe }),
    popover.getByText(rowRe),
  ];

  let optionTarget = null;
  for (const loc of optionCandidates) {
    const first = loc.first();
    try {
      await first.waitFor({ state: 'visible', timeout: 4000 });
      optionTarget = first;
      break;
    } catch { /* next */ }
  }

  if (!optionTarget) {
    const samples = await popover.evaluate((root) => {
      const out = []; const seen = new Set();
      root.querySelectorAll('label, li, div, span').forEach((el) => {
        const r = el.getBoundingClientRect();
        if (r.width === 0 || r.height === 0) return;
        let t = '';
        for (const n of el.childNodes) if (n.nodeType === 3) t += n.nodeValue;
        t = t.trim();
        if (!t || t.length > 60 || seen.has(t)) return;
        seen.add(t); out.push(t);
      });
      return out.slice(0, 50);
    }).catch(() => []);
    throw new Error(`Could not find "${value}" in the filter popover. Visible labels: ${JSON.stringify(samples)}`);
  }

  await optionTarget.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
  await optionTarget.click({ timeout: 5000 });
  await page.waitForTimeout(300);

  // Close the popover so the table re-renders with the filter applied.
  const closeBtn = popover.locator(
    ':is(button,[role="button"],[aria-label*="close" i],.close,[class*="close" i])'
  ).filter({ hasNotText: /clear/i }).first();
  let closed = false;
  if ((await closeBtn.count()) > 0 && (await closeBtn.isVisible().catch(() => false))) {
    await closeBtn.click().catch(() => {});
    closed = true;
  }
  if (!closed || (await popover.isVisible().catch(() => false))) {
    await page.keyboard.press('Escape').catch(() => {});
  }

  await page.waitForLoadState('networkidle', { timeout: 15000 }).catch(() => {});
  await page.waitForTimeout(500);
}

function _resolveRoapField(world, arg, ...keys) {
  _ensureDriveawayData(world);
  const row = (world.driveawayPriceData || [])[0] || {};
  const isPlaceholder = (v) => !v || /^<.*>$/.test(String(v).trim());
  if (!isPlaceholder(arg)) return String(arg).trim();
  for (const k of keys) {
    if (row[k] != null && String(row[k]).trim() !== '') return String(row[k]).trim();
  }
  return '';
}

// ── Lazy-load the "Driveaway Price - Test Data" sheet ───────────────────────
// The Background step ("...found the test data for 'Driveaway Price - Test
// Data'") is a shared no-op, and world.js only eagerly loads a handful of
// sheets (none of them the driveaway one). So the first time any ROAP step
// needs a value we resolve the sheet out of the full Confluence dump that
// world.js stashed on `this.allConfluenceData`.
function _ensureDriveawayData(world) {
  if (Array.isArray(world.driveawayPriceData) && world.driveawayPriceData.length) return;
  const all = world.allConfluenceData || {};
  const key = Object.keys(all).find(k => /driveaway\s*price/i.test(k))
    || Object.keys(all).find(k => /driveaway/i.test(k));
  world.driveawayPriceData = key ? (all[key] || []) : [];
  if (key) {
    console.log(`📋 Loaded "${key}" (${world.driveawayPriceData.length} row/s) into driveawayPriceData`);
  } else {
    console.warn('⚠️  No "Driveaway Price - Test Data" sheet found in Confluence data.');
  }
}

// Attach the request/response intercept listeners once per page (mirrors the
// inline blocks the original steps each duplicated).
function _setupNetworkIntercept(world) {
  if (world._networkInterceptSetup) return;
  world.networkRequests = [];
  world.networkResponses = [];
  world.page.on('request', (req) => {
    (world.networkRequests = world.networkRequests || []).push({ url: req.url(), method: req.method() });
  });
  world.page.on('response', (res) => {
    (world.networkResponses = world.networkResponses || []).push({ url: res.url(), status: res.status() });
  });
  world._networkInterceptSetup = true;
  console.log('📡 Network intercept listeners active');
}

// Capture the calculator's variantpricecalc XHR — its response holds the
// authoritative `finalDriveAwayPrice`, which the verify step prefers over DOM
// scraping. Also pushes the raw XHR into _capturedApiPayloads for the report.
function _setupCpcPriceListener(world) {
  if (world._cpcVariantPriceCalcListenerSetup) return;
  world.cpcDriveawayFromNetwork = null;
  world.page.on('response', async (resp) => {
    try {
      if (!/variantpricecalc/i.test(resp.url())) return;
      if (!resp.ok()) return;
      const bodyText = await resp.text().catch(() => '');
      let json = null;
      try { json = bodyText ? JSON.parse(bodyText) : null; } catch { /* not JSON */ }
      if (json && typeof json.finalDriveAwayPrice === 'number') {
        world.cpcDriveawayFromNetwork = json.finalDriveAwayPrice;
      }
      try {
        const req = resp.request();
        const payload = {
          url: resp.url(),
          method: req.method(),
          requestBody: '',
          requestHeaders: req.headers() || {},
          statusCode: resp.status(),
          responseHeaders: resp.headers() || {},
          responseBody: bodyText,
          timestamp: new Date().toISOString(),
          source: 'roap-variantpricecalc',
        };
        if (Array.isArray(world._capturedApiPayloads)) world._capturedApiPayloads.push(payload);
      } catch { /* ignore */ }
    } catch { /* ignore */ }
  });
  world._cpcVariantPriceCalcListenerSetup = true;
}

// Fill the ROAP login form. Tries the common username/email field patterns,
// then the always-type=password field. Shared by the literal-arg and
// "from test data" username steps.
async function _fillRoapCredentials(page, username, password) {
  assert.ok(username, 'No username available — check "Driveaway Price - Test Data" sheet has a username value.');
  assert.ok(password, 'No password available — check "Driveaway Price - Test Data" sheet has a password value.');

  const userSelectors = [
    'input[type="email"]',
    'input[name*="username" i]',
    'input[id*="username" i]',
    'input[name*="userName" i]',
    'input[id*="userName" i]',
    'input[name*="userId" i]',
    'input[id*="userId" i]',
    'input[name*="login" i]',
    'input[id*="login" i]',
    'input[name*="email" i]',
    'input[id*="email" i]',
    'input[placeholder*="user" i]',
    'input[placeholder*="email" i]',
    'input[aria-label*="user" i]',
    'input[aria-label*="email" i]',
    'form input[type="text"]:visible',
    'input[type="text"]:visible',
  ];
  let userField = null;
  for (const sel of userSelectors) {
    const cand = page.locator(sel).first();
    if ((await cand.count()) > 0 && (await cand.isVisible().catch(() => false))) {
      userField = cand;
      break;
    }
  }
  assert.ok(userField, 'Could not locate a username/email input on the ROAP login page.');
  await userField.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
  await userField.clear().catch(() => {});
  await userField.fill(username);
  console.log(`📋 Filled username: "${username}"`);

  const passField = page.locator('input[type="password"]:visible').first();
  await passField.waitFor({ state: 'visible', timeout: 10000 });
  await passField.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
  await passField.clear().catch(() => {});
  await passField.fill(password);
  console.log('📋 Filled password: "***"');
  await page.waitForTimeout(300);
}

When('I select the Vehicle from test data', async function () {
  const vehicle = _resolveRoapField(this, '', 'Vehicle', 'vehicle', 'Model', 'model');
  assert.ok(vehicle, 'No Vehicle value — check "Driveaway Price - Test Data" has a Vehicle column.');
  console.log(`🖱️  Selecting Vehicle: ${vehicle}`);
  await _selectFromRoapColumnFilter(this.page, { value: vehicle });
  console.log(`✅ Model filter applied: ${vehicle}`);
});

// Variant / Engine / Transmission are not filter popovers in ROAP — they're
// just column values on the rows in the table. After the Model filter narrows
// to one Vehicle's rows, we identify the row whose (Variant, Engine,
// Transmission) cells all match, click it to expand the package sub-row, and
// read the Driveaway price from there. These three steps therefore just stash
// the criteria on `world`; the capture step does the actual row matching and
// price extraction.

When('I select the ROAP Variant from test data', async function () {
  this.roapVariant = _resolveRoapField(this, '',
    'ROAP Variant', 'ROAP_Variant', 'roap_variant', 'Variant', 'variant', 'Variant Group');
  assert.ok(this.roapVariant, 'No Variant value — check "Driveaway Price - Test Data" has a ROAP Variant column.');
  console.log(`📋 ROAP Variant criterion stored: ${this.roapVariant}`);
});

When('I select the ROAP Engine from test data', async function () {
  this.roapEngine = _resolveRoapField(this, '',
    'ROAP Engine', 'ROAP_Engine', 'roap_engine', 'Engine', 'engine');
  assert.ok(this.roapEngine, 'No Engine value — check "Driveaway Price - Test Data" has a ROAP Engine column.');
  console.log(`📋 ROAP Engine criterion stored: ${this.roapEngine}`);
});

When('I select the ROAP Transmission from test data', async function () {
  this.roapTransmission = _resolveRoapField(this, '',
    'ROAP Transmission', 'ROAP_Transmission', 'roap_transmission', 'Transmission', 'transmission');
  assert.ok(this.roapTransmission, 'No Transmission value — check "Driveaway Price - Test Data" has a ROAP Transmission column.');
  console.log(`📋 ROAP Transmission criterion stored: ${this.roapTransmission}`);
});

When('I capture the driveaway price from ROAP', async function () {
  const variant = this.roapVariant || '';
  const engine = this.roapEngine || '';
  const transmission = this.roapTransmission || '';
  assert.ok(variant && engine && transmission,
    `Missing row criteria (variant="${variant}", engine="${engine}", transmission="${transmission}"). Earlier steps must run first.`);

  console.log(`🔎 Finding ROAP row matching Variant="${variant}", Engine="${engine}", Transmission="${transmission}"`);
  await this.page.waitForLoadState('networkidle', { timeout: 10000 }).catch(() => {});
  await this.page.waitForTimeout(500);

  // Locate the body row whose cells contain all three criteria and tag it so
  // Playwright can target it.
  const matchInfo = await this.page.evaluate(({ variant, engine, transmission }) => {
    function visible(el) {
      const r = el.getBoundingClientRect();
      if (r.width === 0 || r.height === 0) return false;
      const cs = window.getComputedStyle(el);
      return cs.visibility !== 'hidden' && cs.display !== 'none';
    }
    function norm(s) { return (s || '').replace(/\s+/g, ' ').trim().toLowerCase(); }
    function rowText(row) {
      const cells = row.querySelectorAll('td, [role="cell"], [class*="cell" i]');
      return Array.from(cells).map(c => norm(c.textContent)).filter(Boolean);
    }
    const wantV = norm(variant), wantE = norm(engine), wantT = norm(transmission);

    // Try classic <tbody><tr>, then role-based row groups.
    const rowSets = [
      Array.from(document.querySelectorAll('tbody tr')).filter(visible),
      Array.from(document.querySelectorAll('[role="row"]')).filter(visible),
      Array.from(document.querySelectorAll('tr')).filter(visible),
    ];
    const samples = [];
    for (const rows of rowSets) {
      for (const row of rows) {
        const cells = rowText(row);
        if (cells.length === 0) continue;
        const joined = cells.join(' | ');
        if (samples.length < 12) samples.push(joined);
        const hit = (w) => cells.some(c => c === w || c.includes(w));
        if (hit(wantV) && hit(wantE) && hit(wantT)) {
          row.setAttribute('data-roap-target', '1');
          return { ok: true, cells };
        }
      }
      if (rows.length > 0) break; // don't fall through if we already saw rows
    }
    return { ok: false, samples };
  }, { variant, engine, transmission });

  if (!matchInfo.ok) {
    throw new Error(`No ROAP row matched all three criteria. Sample rows seen: ${JSON.stringify(matchInfo.samples)}`);
  }
  console.log(`📋 Matched row cells: ${JSON.stringify(matchInfo.cells)}`);

  const matchedRow = this.page.locator('[data-roap-target="1"]').first();
  await matchedRow.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});

  // Click the row checkbox (leftmost cell) to expand the package sub-row.
  // Fall back to clicking the row itself if no checkbox is found.
  const rowCheckbox = matchedRow.locator('input[type="checkbox"]').first();
  if ((await rowCheckbox.count()) > 0) {
    const checked = await rowCheckbox.isChecked().catch(() => false);
    if (!checked) {
      // The visible click target is often a custom wrapper around the input.
      await rowCheckbox.click({ force: true, timeout: 5000 }).catch(async () => {
        await matchedRow.click({ timeout: 5000 });
      });
    }
  } else {
    await matchedRow.click({ timeout: 5000 });
  }
  await this.page.waitForTimeout(800);
  await this.page.waitForLoadState('networkidle', { timeout: 10000 }).catch(() => {});

  // After expanding, the Driveaway package row appears immediately under the
  // matched row, e.g. "Driveaway $20,111 (142)". Search the DOM for that
  // pattern; fall back to the right-side details panel.
  const captured = await this.page.evaluate(() => {
    function visible(el) {
      const r = el.getBoundingClientRect();
      if (r.width === 0 || r.height === 0) return false;
      const cs = window.getComputedStyle(el);
      return cs.visibility !== 'hidden' && cs.display !== 'none';
    }
    const driveawayPriceRe = /drive\s*-?\s*away[^$]*\$\s*([\d,]+(?:\.\d{1,2})?)/i;
    const all = Array.from(document.querySelectorAll('body *')).filter(visible);
    // Prefer the smallest containing element (most specific).
    const matches = [];
    for (const el of all) {
      const t = (el.textContent || '').replace(/\s+/g, ' ').trim();
      if (!t || t.length > 200) continue;
      const m = t.match(driveawayPriceRe);
      if (m) {
        const r = el.getBoundingClientRect();
        matches.push({ text: t, price: m[1], area: r.width * r.height });
      }
    }
    if (matches.length === 0) return { error: 'No "Driveaway $..." text found after row expand.' };
    matches.sort((a, b) => a.area - b.area);
    return { text: matches[0].price, context: matches[0].text };
  });

  if (captured.error) {
    throw new Error(captured.error);
  }
  const num = Number.parseFloat(String(captured.text).replace(/[^0-9.]/g, ''));
  if (!Number.isFinite(num)) {
    throw new Error(`Captured driveaway value "${captured.text}" is not a number.`);
  }
  this.roapDriveawayPrice = num;
  this.roapDriveawayPriceText = `$${captured.text}`;
  console.log(`📌 Captured ROAP Driveaway price: $${captured.text} (from: "${captured.context}")`);

  // Save a dedicated screenshot of the ROAP page so it's included in the
  // report alongside the consumer-site one (mirrors PIM's behaviour).
  try {
    const dir = 'screenshots';
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    const vehicleTag = (this.driveawayPriceData?.[0]?.Vehicle || 'ROAP')
      .toString().replace(/[^a-zA-Z0-9]/g, '_');
    const ts = new Date().toISOString().replace(/[:.]/g, '-');
    const file = path.join(dir, `roap-Driveaway-${vehicleTag}-${ts}.png`);
    const buf = await this.page.screenshot({ fullPage: true });
    fs.writeFileSync(file, buf);
    if (typeof this.attach === 'function') this.attach(buf, 'image/png');
    this.roapScreenshotPath = file;
    console.log(`📸 ROAP Driveaway screenshot saved: ${file}`);
  } catch (err) {
    console.warn(`⚠️  Failed to save ROAP screenshot: ${err.message}`);
  }

  // Clean up the tag so it doesn't linger for the next scenario.
  await this.page.evaluate(() => {
    document.querySelectorAll('[data-roap-target]').forEach(el => el.removeAttribute('data-roap-target'));
  }).catch(() => {});
});

When('I navigate to the calculator page', async function () {
  // Read CPC URL from the "Driveaway Price - Test Data" sheet loaded by
  // the Background step.
  _ensureDriveawayData(this);
  const row = (this.driveawayPriceData || [])[0] || {};
  const target = (row['CPC URL'] || row.CPCURL || row.cpc_url || row.cpcUrl || row.CpcUrl || row.URL || row.url || '').toString().trim();
  assert.ok(/^https?:\/\//i.test(target), `CPC URL is not a valid http(s) URL: "${target}". Check the "Driveaway Price - Test Data" sheet has a CPC URL value.`);

  // Setup network intercept listeners (captures all requests/responses for this page)
  if (!this._networkInterceptSetup) {
    this.networkRequests = [];
    this.networkResponses = [];
    this.page.on('request', (req) => {
      (this.networkRequests = this.networkRequests || []).push({ url: req.url(), method: req.method() });
    });
    this.page.on('response', async (res) => {
      (this.networkResponses = this.networkResponses || []).push({ url: res.url(), status: res.status() });
    });
    this._networkInterceptSetup = true;
    console.log('📡 Network intercept listeners active');
  }

  // Capture the variantpricecalc XHR — its response has the authoritative
  // `finalDriveAwayPrice` value, more reliable than DOM scraping. Also push
  // the raw XHR into _capturedApiPayloads so the report's payload panel
  // shows the full request/response (mirrors PIM's MLP capture).
  if (!this._cpcVariantPriceCalcListenerSetup) {
    this.cpcDriveawayFromNetwork = null;
    this.page.on('response', async (resp) => {
      try {
        if (!/variantpricecalc/i.test(resp.url())) return;
        if (!resp.ok()) return;
        const bodyText = await resp.text().catch(() => '');
        let json = null;
        try { json = bodyText ? JSON.parse(bodyText) : null; } catch { /* not JSON */ }
        if (json && typeof json.finalDriveAwayPrice === 'number') {
          this.cpcDriveawayFromNetwork = json.finalDriveAwayPrice;
        }
        try {
          const req = resp.request();
          const payload = {
            url: resp.url(),
            method: req.method(),
            requestBody: '',
            requestHeaders: req.headers() || {},
            statusCode: resp.status(),
            responseHeaders: resp.headers() || {},
            responseBody: bodyText,
            timestamp: new Date().toISOString(),
            source: 'roap-variantpricecalc',
          };
          if (Array.isArray(this._capturedApiPayloads)) {
            this._capturedApiPayloads.push(payload);
          }
        } catch { /* ignore */ }
      } catch { /* ignore */ }
    });
    this._cpcVariantPriceCalcListenerSetup = true;
  }

  console.log(`📋 Navigating to calculator: ${target}`);
  await this.page.goto(target, { waitUntil: 'domcontentloaded', timeout: 60000 });
  await this.page.waitForLoadState('networkidle', { timeout: 30000 }).catch(() => {});
  await this.page.waitForTimeout(2000);
});

// ─── Calculator page (consumer site) ────────────────────────────────────────
// These steps mirror PIM_auto.steps.js's consumer-site flow. The Hyundai
// calculator opens a "Set your location" modal on first visit — postcode,
// suburb and Set-dealer are all handled by the shared `handleLocationModal`
// helper, so we trigger it from the postcode step. The two follow-up steps
// then become no-ops because the modal is already dismissed.

function _isNa(v) {
  if (!v) return true;
  const s = String(v).trim().toLowerCase();
  return s === '' || s === 'na' || s === 'n/a' || s === '-';
}

When('I enter postcode from test data', async function () {
  const postcode = _resolveRoapField(this, '', 'postcode', 'Postcode', 'POSTCODE') || '2000';
  console.log(`📍 Handling location modal with postcode: ${postcode}`);
  await handleLocationModal(this.page, postcode);
  this._locationDismissed = true;
});

When('I select the suburb from test data', async function () {
  // handleLocationModal (called by the postcode step) already picks the first
  // suburb result. Nothing to do here.
  if (this._locationDismissed) {
    console.log('ℹ️  Suburb already selected by location modal — no-op');
    return;
  }
  console.log('ℹ️  Location modal was not dismissed by postcode step; nothing to do');
});

When('I click on {string} button', async function (buttonName) {
  // Set dealer was clicked inside handleLocationModal, so skip duplicate clicks.
  if (/^\s*set\s+dealer\s*$/i.test(buttonName) && this._locationDismissed) {
    console.log('ℹ️  "Set dealer" already clicked by location modal — no-op');
    return;
  }
  await this.clickButton(buttonName);
  await this.page.waitForTimeout(1000);
});

When('I select Site_Variant {string} from test data', async function (variantArg) {
  const variant = _resolveRoapField(this, variantArg,
    'Site_Variant', 'Site Variant', 'SiteVariant', 'site_variant');
  assert.ok(variant, 'No Site_Variant — check "Driveaway Price - Test Data".');
  await selectConsumerVariant(this.page, variant);
});

When('I select Site_Powertrain {string} from test data', async function (powerArg) {
  const powertrain = _resolveRoapField(this, powerArg,
    'Site_Powertrain', 'Site Powertrain', 'SitePowertrain', 'site_powertrain', 'Powertrain');
  if (_isNa(powertrain)) {
    console.log('ℹ️  No Site_Powertrain to select (NA) — skipping');
    return;
  }
  await selectConsumerOption(this.page, powertrain);
});

When('I select Extended Range Option Pack from test data', async function () {
  const option = _resolveRoapField(this, '',
    'Extended Range Option Pack', 'ExtendedRangeOptionPack', 'extended_range_option_pack');
  if (_isNa(option)) {
    console.log('ℹ️  No Extended Range Option Pack to select (NA) — skipping');
    return;
  }
  await selectConsumerOption(this.page, option);
});

When('I select Roof Basket Option Pack from test data', async function () {
  const option = _resolveRoapField(this, '',
    'Roof Basket Option Pack', 'RoofBasketOptionPack', 'roof_basket_option_pack');
  if (_isNa(option)) {
    console.log('ℹ️  No Roof Basket Option Pack to select (NA) — skipping');
    return;
  }
  await selectConsumerOption(this.page, option);
});

When('I select Site_Transmission {string} from test data', async function (transArg) {
  const transmission = _resolveRoapField(this, transArg,
    'Site_Transmission', 'Site Transmission', 'SiteTransmission', 'site_transmission', 'Transmission');
  if (_isNa(transmission)) {
    console.log('ℹ️  No Site_Transmission to select (NA) — skipping');
    return;
  }
  await selectConsumerOption(this.page, transmission);
});

Then('I verify the captured driveaway price matches on calculator page', async function () {
  const roapPrice = this.roapDriveawayPrice;
  assert.ok(Number.isFinite(roapPrice),
    'ROAP Driveaway price was not captured — the capture step must run first.');

  // The authoritative consumer value comes from the variantpricecalc XHR
  // response (finalDriveAwayPrice). Give any in-flight request a brief
  // window to land, then fall back to scraping the popup if necessary.
  if (!Number.isFinite(this.cpcDriveawayFromNetwork)) {
    await this.page
      .waitForResponse(r => /variantpricecalc/i.test(r.url()) && r.ok(), { timeout: 8000 })
      .catch(() => null);
  }
  await this.page.waitForLoadState('networkidle', { timeout: 5000 }).catch(() => {});
  await this.page.waitForTimeout(800);

  let cpcPrice = null;
  let source = '';
  if (Number.isFinite(this.cpcDriveawayFromNetwork)) {
    cpcPrice = this.cpcDriveawayFromNetwork;
    source = 'network (variantpricecalc.finalDriveAwayPrice)';
  } else {
    const captured = await this.page.evaluate(() => {
      function visible(el) {
        const r = el.getBoundingClientRect();
        if (r.width === 0 || r.height === 0) return false;
        const cs = window.getComputedStyle(el);
        return cs.visibility !== 'hidden' && cs.display !== 'none';
      }
      const labelRe = /drive\s*-?\s*away|driveaway/i;
      const all = Array.from(document.querySelectorAll('body *')).filter(visible);
      const hits = [];
      for (const el of all) {
        const t = (el.textContent || '').replace(/\s+/g, ' ').trim();
        if (!t || t.length > 200) continue;
        if (!labelRe.test(t)) continue;
        const m = t.match(/\$\s*([\d,]+(?:\.\d{1,2})?)/);
        if (!m) continue;
        const r = el.getBoundingClientRect();
        hits.push({ text: t, price: m[1], area: r.width * r.height });
      }
      if (hits.length === 0) return { error: 'No "Driveaway $..." text found on calculator price summary.' };
      hits.sort((a, b) => a.area - b.area);
      return { text: hits[0].price, context: hits[0].text };
    });
    if (captured.error) throw new Error(captured.error);
    cpcPrice = Number.parseFloat(String(captured.text).replace(/[^0-9.]/g, ''));
    assert.ok(Number.isFinite(cpcPrice), `Calculator driveaway "${captured.text}" is not a number.`);
    source = `popup DOM ("${captured.context}")`;
  }

  this.cpcDriveawayPrice = cpcPrice;
  console.log(`📌 Calculator Driveaway price: $${cpcPrice.toLocaleString()} [source: ${source}]`);
  console.log(`📊 Comparison — ROAP: $${roapPrice.toLocaleString()}  |  Calculator: $${cpcPrice.toLocaleString()}`);

  // Compare whole-dollar amounts only (ignore cent rounding differences).
  assert.strictEqual(
    Math.trunc(cpcPrice),
    Math.trunc(roapPrice),
    `Driveaway price mismatch — ROAP $${roapPrice} vs Calculator $${cpcPrice}`
  );
  console.log('✅ Driveaway prices match (whole-dollar).');
});

// ── Auto-appended steps ──────────────────────────────────────────

Given('I navigate to the ROAP login page {string}', async function (url) {
  // The feature has no Examples table, so `url` arrives as the literal
  // placeholder "<roap_url>". Resolve the real URL from the test-data sheet.
  const target = _resolveRoapField(this, url, 'roap_url', 'ROAP URL', 'ROAP_URL', 'url', 'URL');
  assert.ok(/^https?:\/\//i.test(target),
    `ROAP URL is not a valid http(s) URL: "${target}". Check the "Driveaway Price - Test Data" sheet has a roap_url value.`);
  _setupNetworkIntercept(this);
  console.log(`📋 Navigating to ROAP login: ${target}`);
  await this.page.goto(target, { waitUntil: 'domcontentloaded', timeout: 60000 });
  await this.page.waitForLoadState('networkidle', { timeout: 30000 }).catch(() => {});
  await this.page.waitForTimeout(2000);
});

When('I enter username {string} and password {string}', async function (userArg, passArg) {
  const username = _resolveRoapField(this, userArg, 'username', 'Username', 'user name', 'email', 'Email');
  const password = _resolveRoapField(this, passArg, 'password', 'Password', 'pass');
  await _fillRoapCredentials(this.page, username, password);
});

When('I select the Vehicle {string} from the table', async function (vehicleArg) {
  const vehicle = _resolveRoapField(this, vehicleArg, 'Vehicle', 'vehicle', 'Model', 'model');
  assert.ok(vehicle, 'No Vehicle value — check "Driveaway Price - Test Data" has a Vehicle column.');
  console.log(`🖱️  Selecting Vehicle via Model filter: ${vehicle}`);
  await _selectFromRoapColumnFilter(this.page, { value: vehicle });
  console.log(`✅ Model filter applied: ${vehicle}`);
});

// Variant / Engine / Transmission are column values on the table rows (not
// filter popovers). Stash the criteria; the capture step matches the row.
When('I select the ROAP Variant {string} from the table', async function (variantArg) {
  this.roapVariant = _resolveRoapField(this, variantArg,
    'ROAP Variant', 'ROAP_Variant', 'roap_variant', 'Variant', 'variant', 'Variant Group');
  assert.ok(this.roapVariant, 'No Variant value — check "Driveaway Price - Test Data" has a ROAP Variant column.');
  console.log(`📋 ROAP Variant criterion stored: ${this.roapVariant}`);
});

When('I select the ROAP Engine {string} from the table', async function (engineArg) {
  this.roapEngine = _resolveRoapField(this, engineArg,
    'ROAP Engine', 'ROAP_Engine', 'roap_engine', 'Engine', 'engine');
  assert.ok(this.roapEngine, 'No Engine value — check "Driveaway Price - Test Data" has a ROAP Engine column.');
  console.log(`📋 ROAP Engine criterion stored: ${this.roapEngine}`);
});

When('I select the ROAP Transmission {string} from the table', async function (transArg) {
  this.roapTransmission = _resolveRoapField(this, transArg,
    'ROAP Transmission', 'ROAP_Transmission', 'roap_transmission', 'Transmission', 'transmission');
  assert.ok(this.roapTransmission, 'No Transmission value — check "Driveaway Price - Test Data" has a ROAP Transmission column.');
  console.log(`📋 ROAP Transmission criterion stored: ${this.roapTransmission}`);
});

When('I navigate to the calculator page {string}', async function (url) {
  const target = _resolveRoapField(this, url,
    'CPC URL', 'CPCURL', 'cpc_url', 'cpcUrl', 'CpcUrl', 'URL', 'url');
  assert.ok(/^https?:\/\//i.test(target),
    `CPC URL is not a valid http(s) URL: "${target}". Check the "Driveaway Price - Test Data" sheet has a CPC URL value.`);
  _setupNetworkIntercept(this);
  _setupCpcPriceListener(this);
  console.log(`📋 Navigating to calculator: ${target}`);
  await this.page.goto(target, { waitUntil: 'domcontentloaded', timeout: 60000 });
  await this.page.waitForLoadState('networkidle', { timeout: 30000 }).catch(() => {});
  await this.page.waitForTimeout(2000);
});

When('I enter postcode {string} in the postcode field', async function (postcodeArg) {
  // The Hyundai calculator opens a "Set your location" modal on first visit.
  // handleLocationModal fills the postcode, picks the first suburb result and
  // clicks "Set dealer" — so the suburb/Set-dealer steps become no-ops.
  const postcode = _resolveRoapField(this, postcodeArg, 'postcode', 'Postcode', 'POSTCODE') || '2000';
  console.log(`📍 Handling location modal with postcode: ${postcode}`);
  await handleLocationModal(this.page, postcode);
  this._locationDismissed = true;
});

When('I select the suburb {string} from the dropdown', async function (suburbArg) {
  // The suburb was already picked inside handleLocationModal (postcode step).
  if (this._locationDismissed) {
    console.log('ℹ️  Suburb already selected by location modal — no-op');
    return;
  }
  console.log(`ℹ️  Location modal not dismissed; nothing to do for suburb "${suburbArg}"`);
});

When('I select Extended Range Option Pack {string} from test data', async function (optionArg) {
  const option = _resolveRoapField(this, optionArg,
    'Extended Range Option Pack', 'ExtendedRangeOptionPack', 'extended_range_option_pack');
  if (_isNa(option)) {
    console.log('ℹ️  No Extended Range Option Pack to select (NA) — skipping');
    return;
  }
  await selectConsumerOption(this.page, option);
});

When('I select Roof Basket Option Pack {string} from test data', async function (optionArg) {
  const option = _resolveRoapField(this, optionArg,
    'Roof Basket Option Pack', 'RoofBasketOptionPack', 'roof_basket_option_pack');
  if (_isNa(option)) {
    console.log('ℹ️  No Roof Basket Option Pack to select (NA) — skipping');
    return;
  }
  await selectConsumerOption(this.page, option);
});

// ── Auto-appended steps ──────────────────────────────────────────

// ─────────────────────────────────────────────────────────────────────────────
// PIM-based ROAP ↔ CPC price verification (@DriveawayPrice flow).
//
// A single "Pim" value from the "Driveaway Price - Test Data" sheet keys both
// sides: it locates the ROAP Offers-table row (Pim column) and the matching CPC
// carpricecalculator variant (a Pim field in the response). This replaces the
// old FCAI key, which is being removed from ROAP.
//
// Field mapping (live-data verified, user-confirmed):
//   ROAP MLP        ==  CPC carpricecalculator `price`
//   ROAP Driveaway  ==  CPC carpricecalculator `priceEstimate`
// for the CPC variant whose Pim value equals the test-data Pim.
// ─────────────────────────────────────────────────────────────────────────────

const _toNum = (s) => {
  const n = Number.parseFloat(String(s == null ? '' : s).replace(/[^0-9.]/g, ''));
  return Number.isFinite(n) ? n : NaN;
};

// ── "Driveaway price is not available" reporting ────────────────────────────
// Not every model carries a driveaway offer. That is a legitimate data state,
// not a broken test, so the steps record a plain-English note instead of
// failing with a selector-level message. world.js writes `scenarioNote` into
// the scenario metadata JSON, which generateReport.js shows in the report's
// Summary column.
function _driveawayModelLabel(world) {
  const row = (world.driveawayPriceData || [])[0] || {};
  const model = world.roapModel || row.Vehicle || row.model_slug || '';
  const pim = world.pim ? `Pim ${world.pim}` : '';
  const bits = [model, pim].filter(Boolean).join(', ');
  return bits || 'this model';
}

function _setScenarioNote(world, note) {
  world.scenarioNote = note;
  world.driveawayNote = note;
  try { if (typeof world.attach === 'function') world.attach(note, 'text/plain'); } catch { /* ignore */ }
}

// Extract the identifying + price fields from a parsed `variantpricecalculator`
// response. That response describes ONE fully-specified vehicle config:
//   pimId               -> the PIM identifier (matches the test-data Pim)
//   mlpFromPIM / mlp    -> Manufacturer List Price
//   finalDriveAwayPrice -> Drive Away price (priceEstimate as fallback)
// Fields are found by a case-insensitive deep walk so nesting doesn't matter.
function _extractPimRecord(json) {
  let pimId = null, mlp = null, driveaway = null, variantId = null, description = null;
  const visit = (o, depth = 0) => {
    if (!o || depth > 10 || typeof o !== 'object') return;
    if (Array.isArray(o)) { for (const x of o) visit(x, depth + 1); return; }
    for (const [k, v] of Object.entries(o)) {
      const kl = k.toLowerCase();
      if (pimId == null && kl === 'pimid' && v != null && v !== '') pimId = String(v).trim();
      if (kl === 'mlpfrompim' && typeof v === 'number') mlp = v;
      else if (mlp == null && kl === 'mlp' && typeof v === 'number') mlp = v;
      if (kl === 'finaldriveawayprice' && typeof v === 'number') driveaway = v;
      else if (driveaway == null && kl === 'priceestimate' && typeof v === 'number') driveaway = v;
      if (kl === 'variantid' && v != null) variantId = String(v);
      if (!description && kl === 'description' && typeof v === 'string') description = v;
      if (v && typeof v === 'object') visit(v, depth + 1);
    }
  };
  visit(json);
  return { pimId, mlp, driveaway, variantId, description };
}

// Read the identifying + price fields an object owns DIRECTLY (no descent).
const _ownPimRecord = (o) => {
  let pimId = null, mlp = null, driveaway = null, variantId = null, description = null;
  for (const [k, v] of Object.entries(o)) {
    const kl = k.toLowerCase();
    if (kl === 'pimid' && v != null && v !== '') pimId = String(v).trim();
    if (kl === 'mlpfrompim' && typeof v === 'number') mlp = v;
    else if (mlp == null && kl === 'mlp' && typeof v === 'number') mlp = v;
    if (kl === 'finaldriveawayprice' && typeof v === 'number') driveaway = v;
    else if (driveaway == null && kl === 'priceestimate' && typeof v === 'number') driveaway = v;
    if (kl === 'variantid' && v != null) variantId = String(v);
    if (!description && kl === 'description' && typeof v === 'string') description = v;
  }
  return { pimId, mlp, driveaway, variantId, description };
};

// A variantpricecalculator payload sometimes nests sibling variants alongside
// the selected one. Harvest every object that carries a pimId AND both of its
// own prices — a sibling can satisfy the lookup without us ever having to click
// through to that combination. The "owns its prices" rule is deliberate: a deep
// walk would happily pair one variant's pimId with another's price.
function _extractOwnPimRecords(json) {
  const out = []; const seen = new Set();
  const visit = (o, depth = 0) => {
    if (!o || depth > 12 || typeof o !== 'object') return;
    if (Array.isArray(o)) { for (const x of o) visit(x, depth + 1); return; }
    const rec = _ownPimRecord(o);
    if (rec.pimId != null && typeof rec.mlp === 'number' && typeof rec.driveaway === 'number'
        && !seen.has(rec.pimId)) { seen.add(rec.pimId); out.push(rec); }
    for (const v of Object.values(o)) if (v && typeof v === 'object') visit(v, depth + 1);
  };
  visit(json);
  return out;
}

// Depth-first walk of the calculator's option groups (energy type × variant ×
// powertrain × transmission × option packs), re-reading the LIVE groups after
// each selection because they are variant-dependent. A `variantpricecalculator`
// XHR fires on every selection, so after each successful click we call the async
// `shouldStop()` — the caller checks whether the matching pimId has arrived and
// aborts the walk as soon as it has. Returns { found, aborted, clicks }.
// Adapted from the same marker-click traversal used by calculator_pricing.
async function _cpcSelectAllCombosUntil(page, shouldStop, walkOpts = {}) {
  const { clickCap = 400, packsFirst = true } = walkOpts;
  const GROUP_RE_SRC = '^(select energy type|body type|select variant|choose your powertrain|transmission)\\.?$';

  const getGroups = () => page.evaluate(({ reSrc, packsFirst }) => {
    const groupRe = new RegExp(reSrc, 'i'); const packRe = /option\s+pack/i;
    const isGH = t => groupRe.test(t) || packRe.test(t);
    const seen = new Set(); const out = [];
    for (const el of document.querySelectorAll('h1,h2,h3,h4')) {
      if (el.offsetParent === null) continue;
      const t = (el.innerText || '').trim();
      if (!isGH(t)) continue;
      const name = t.replace(/\.$/, ''); const key = name.toLowerCase();
      if (seen.has(key)) continue; seen.add(key); out.push(name);
    }
    // Energy type gates the available powertrain/variant pricing, so it must be
    // chosen FIRST (selecting a variant while the wrong energy type is active,
    // then toggling energy, resets the variant).
    //
    // Option packs GATE the powertrain list: on KONA Electric, "N Line Option
    // Pack = Yes" leaves only Extended Range 150kW selectable, while "No" offers
    // Standard Range 99kW as well. Enumerating the powertrain BEFORE the pack
    // reads that list under whatever pack state leaked in from the previous
    // branch — which is why the walk returned exactly one powertrain per variant
    // (KONA/No/Standard, KONA/Yes/Extended) instead of the full 2×2 grid.
    // Order: energy → variant → option packs → powertrain → transmission.
    // `packsFirst: false` restores the old ordering for the second pass, in case
    // a model constrains the pack by the powertrain rather than the other way up.
    const rank = (name) => {
      const n = name.toLowerCase();
      if (/energy type|body type/.test(n)) return 0;
      if (/select variant/.test(n)) return 1;
      if (packRe.test(n)) return packsFirst ? 2 : 5;
      if (/powertrain/.test(n)) return 3;
      if (/transmission/.test(n)) return 4;
      return 6;
    };
    out.sort((a, b) => rank(a) - rank(b));
    return out;
  }, { reSrc: GROUP_RE_SRC, packsFirst });

  const getOptions = (groupName) => page.evaluate(({ groupName, reSrc }) => {
    const groupRe = new RegExp(reSrc, 'i'); const packRe = /option\s+pack/i;
    const sectionRe = /^(select energy type|body type|select variant|choose your powertrain|transmission|colour|drive away price|finance|hyundai finance|novated lease|warranty|servicing|accessories|interior|exterior)\.?$/i;
    const isGH = t => groupRe.test(t) || packRe.test(t);
    const norm = groupName.trim().toLowerCase().replace(/\.$/, '');
    const allEls = Array.from(document.querySelectorAll('*'));
    const heading = Array.from(document.querySelectorAll('h1,h2,h3,h4'))
      .find(el => el.offsetParent !== null && (el.innerText || '').trim().toLowerCase().replace(/\.$/, '') === norm);
    if (!heading) return null;
    const startIdx = allEls.indexOf(heading);
    const options = []; const seen = new Set();
    for (let i = startIdx + 1; i < allEls.length; i++) {
      const el = allEls[i];
      if (!el || el.offsetParent === null) continue;
      const t = (el.innerText || '').trim();
      if (/^H[1-4]$/.test(el.tagName)) {
        if (sectionRe.test(t) && !groupRe.test(t)) break;
        if (isGH(t) && t.toLowerCase().replace(/\.$/, '') !== norm) break;
        continue;
      }
      // Tile shape varies a LOT between models: an EV variant/powertrain tile
      // carries a price line, a range/kW spec and sometimes a badge, so it is
      // taller and more deeply nested than a petrol one. Keep these bounds
      // loose — a junk label costs one cheap no-op click, but a dropped label
      // silently deletes a whole combination branch from the sweep (this is
      // what hid the KONA Electric powertrain options).
      if (el.children.length > 6) continue;
      const r = el.getBoundingClientRect();
      if (r.width < 80 || r.height < 24 || r.height > 220) continue;
      if (!t || t.length > 200) continue;
      const label = t.split(/\n+/).map(s => s.trim()).filter(Boolean)[0];
      if (!label || label.length > 80) continue;
      if (/\$/.test(label)) continue; // a price line is not an option label
      if (/^(find what|select|change vehicle|choose|what's detailed|whats detailed)/i.test(label)) continue;
      if (seen.has(label)) continue;
      seen.add(label); options.push(label.slice(0, 100));
      if (options.length >= 24) break;
    }
    return options;
  }, { groupName, reSrc: GROUP_RE_SRC });

  const markOption = (groupName, label) => page.evaluate(({ groupName, label }) => {
    document.querySelectorAll('[data-pw-target]').forEach(el => el.removeAttribute('data-pw-target'));
    const normGroup = groupName.trim().toLowerCase().replace(/\.$/, '');
    const normLabel = label.trim().toLowerCase();
    const headings = Array.from(document.querySelectorAll('h1,h2,h3,h4')).filter(el => el.offsetParent !== null);
    const heading = headings.find(el => (el.innerText || '').trim().toLowerCase().replace(/\.$/, '') === normGroup);
    if (!heading) return { ok: false };
    const hIdx = headings.indexOf(heading);
    const nextHeading = headings[hIdx + 1] || null;
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_ELEMENT);
    const candidates = []; let inRange = false;
    while (walker.nextNode()) {
      const el = walker.currentNode;
      if (el === heading) { inRange = true; continue; }
      if (nextHeading && el === nextHeading) break;
      if (!inRange || el.offsetParent === null) continue;
      // Must stay >= the limit getOptions uses, or a tile can be enumerated as
      // an option and then be unclickable. EV powertrain tiles carry a title, a
      // subtitle and a "+ Driveaway Offer" badge, which puts them over 4.
      if (el.children.length > 6) continue;
      const t = (el.innerText || '').trim(); if (!t) continue;
      const firstLine = t.split(/\n+/).map(s => s.trim()).filter(Boolean)[0] || '';
      if (firstLine.toLowerCase() !== normLabel) continue;
      if (/^H[1-4]$/.test(el.tagName)) continue;
      candidates.push(el);
    }
    if (!candidates.length) return { ok: false };
    const isClickable = (el) => {
      if (!el || el === document.body) return false;
      if (el.tagName === 'BUTTON' || el.tagName === 'A') return true;
      const role = el.getAttribute && el.getAttribute('role');
      if (['button', 'tab', 'radio', 'option'].includes(role)) return true;
      if (el.hasAttribute && el.hasAttribute('tabindex')) return true;
      const clsStr = (el.className || '').toString();
      const cls = clsStr.split(/\s+/);
      if (cls.includes('cpc-option')) return true;
      if (cls.some(t => /^(option-tile|tile|btn|button|card|chip)$/i.test(t))) return true;
      if (/cursor-pointer/.test(clsStr)) return true;
      return false;
    };
    const findClickable = (start) => { let el = start; for (let i = 0; i < 6 && el && el !== document.body; i++) { if (isClickable(el)) return el; el = el.parentElement; } return start; };
    const isSelected = (el) => {
      if (!el) return false;
      const g = a => el.getAttribute && el.getAttribute(a) === 'true';
      if (g('aria-selected') || g('aria-checked') || g('aria-pressed')) return true;
      return /\b(selected|active|is-selected|is-active|checked)\b/i.test((el.className || '').toString());
    };
    const resolved = [];
    for (const c of candidates) { const cl = findClickable(c); if (isClickable(cl) && !resolved.includes(cl)) resolved.push(cl); }
    const pool = resolved.length ? resolved : [findClickable(candidates[0])];
    let target = pool.find(el => !isSelected(el)); const alreadySelected = !target;
    if (!target) target = pool[0];
    target.setAttribute('data-pw-target', '1');
    return { ok: true, alreadySelected };
  }, { groupName, label });

  // Returns 'clicked' | 'already' | false (both strings are truthy).
  // Re-clicking an option that is ALREADY active fires no variantpricecalculator
  // XHR, so waiting the full 10s on it is dead time — and single-option groups
  // (powertrain/transmission on most models) are always in that state. On KONA
  // that alone was ~4 minutes of the walk, which is why the deep combination
  // pass never got through the Electric branch before the run was torn down.
  const clickOption = async (groupName, label) => {
    const found = await markOption(groupName, label);
    if (!found || !found.ok) return false;
    const already = !!found.alreadySelected;
    const target = page.locator('[data-pw-target="1"]');
    try {
      await target.scrollIntoViewIfNeeded({ timeout: 4000 });
      await target.click({ timeout: 5000 });
    } catch {
      try {
        await page.evaluate(() => document.querySelector('[data-pw-target="1"]')?.scrollIntoView({ block: 'center', inline: 'center' })).catch(() => {});
        await page.waitForTimeout(200);
        await target.click({ timeout: 5000, force: true });
      } catch {
        await page.evaluate(() => document.querySelector('[data-pw-target="1"]')?.removeAttribute('data-pw-target')).catch(() => {});
        return false;
      }
    }
    await page.evaluate(() => document.querySelector('[data-pw-target="1"]')?.removeAttribute('data-pw-target')).catch(() => {});
    // The trusted click triggers a variantpricecalculator XHR — wait for it so
    // the caller's shouldStop() sees the freshly-captured pimId.
    await page.waitForResponse(r => /variantpricecalc/i.test(r.url()) && r.ok(), { timeout: already ? 1500 : 10000 }).catch(() => null);
    await page.waitForTimeout(already ? 150 : 400);
    return already ? 'already' : 'clicked';
  };

  // `stop` = the caller's shouldStop() fired (target found). `aborted` = the walk
  // ended early for any other reason (page closed, click cap). Keeping these
  // apart matters: the old code set one flag for both, so a browser that died
  // mid-walk was reported as "after selecting all combinations" when in fact
  // most combinations were never tried.
  let stop = false, aborted = false, clicks = 0;
  const MAX_DEPTH = 8;
  const isFatal = (e) => /Target page, context or browser has been closed|Execution context was destroyed/i.test((e && e.message) || '');

  // Wait for the calculator's selectable option UI to render — right after the
  // dealer is set the page can still be hydrating, and enumerating too early
  // returns empty group/variant lists (so only the default variant is seen).
  for (let i = 0; i < 40; i++) {
    const groups = await getGroups().catch(() => []);
    const vg = groups.find(g => /select variant/i.test(g));
    if (vg) {
      const o = await getOptions(vg).catch(() => null);
      if (o && o.length) break;
    }
    await page.waitForTimeout(500);
  }

  // ONE depth-first walk over the FULL cartesian product of the live option
  // groups — energy/body → variant → powertrain → transmission → option packs.
  // Options are re-read at every level because each group's contents depend on
  // the selections above it (KONA exposes one powertrain under Petrol/Hybrid but
  // two — Standard Range / Extended Range — under Electric), so a model's real
  // combination set can only be discovered as the walk descends.
  //
  // There used to be a "fast pass" over energy × variant ahead of this walk. It
  // covered every combination only for models whose powertrain and transmission
  // groups have a single option each, and left the deep walk to redo everything
  // from scratch. shouldStop() is checked after every single selection here, so
  // the walk reaches the common case just as quickly without the duplication.
  const dfs = async (handled, path) => {
    if (stop || clicks >= clickCap) return;
    let groups = [];
    try { groups = await getGroups(); } catch (e) { if (isFatal(e)) { stop = true; aborted = true; } return; }
    const nextGroup = groups.find(g => !handled.has(g.toLowerCase()));
    if (!nextGroup || handled.size >= MAX_DEPTH) { if (await shouldStop()) stop = true; return; }
    const nextHandled = new Set(handled); nextHandled.add(nextGroup.toLowerCase());
    let opts = null;
    try { opts = await getOptions(nextGroup); } catch (e) { if (isFatal(e)) { stop = true; aborted = true; return; } }
    if (!opts || !opts.length) return dfs(nextHandled, path);
    console.log(`   ${'  '.repeat(handled.size)}${nextGroup}: ${opts.join(' | ')}${path ? `   [under ${path}]` : ''}`);
    let selectedAny = false;
    for (const opt of opts) {
      if (stop || clicks >= clickCap) break;
      let ok = false;
      try { ok = await clickOption(nextGroup, opt); clicks++; } catch (e) { if (isFatal(e)) { stop = true; aborted = true; break; } }
      if (!ok) { console.log(`   ${'  '.repeat(handled.size)}⚠️  could not select "${opt}" in ${nextGroup}`); continue; }
      selectedAny = true;
      if (await shouldStop()) { stop = true; break; }
      await dfs(nextHandled, path ? `${path} › ${opt}` : opt);
    }
    // Nothing in this group was selectable (labels moved, tiles disabled) —
    // don't let it block the groups below it; carry on in the current state.
    if (!selectedAny && !stop) await dfs(nextHandled, path);
  };
  await dfs(new Set(), '');
  if (clicks >= clickCap) {
    aborted = true;
    console.warn(`⚠️  Combination walk hit the ${clickCap}-click cap — the sweep is INCOMPLETE.`);
  }
  return { found: stop && !aborted, aborted, clicks };
}

// Scan the ROAP Offers table for the row whose Pim column equals `pim` and tag
// it with data-roap-target="1". Columns are resolved by header text (Pim / MLP /
// Model / Variant Group) so they survive column reorders (e.g. FCAI removal).
// Scrolls to load lazily-rendered rows.
async function _tagRoapPimRow(page, pim) {
  const scan = () => page.evaluate((pim) => {
    const norm = s => (s || '').replace(/\s+/g, ' ').trim();
    document.querySelectorAll('[data-roap-target]').forEach(e => e.removeAttribute('data-roap-target'));
    for (const t of Array.from(document.querySelectorAll('table'))) {
      const rows = Array.from(t.querySelectorAll('tr'));
      const header = rows.find(r => /\bPIM\b/i.test(r.innerText) && /\bMLP\b/i.test(r.innerText));
      if (!header) continue;
      const heads = Array.from(header.querySelectorAll('th,td')).map(c => norm(c.innerText));
      const pimIdx = heads.findIndex(h => /^pim$/i.test(h));
      const mlpIdx = heads.findIndex(h => /^mlp$/i.test(h));
      const modelIdx = heads.findIndex(h => /^model/i.test(h));
      const vgIdx = heads.findIndex(h => /variant\s*group/i.test(h));
      if (pimIdx === -1) continue;
      const mi = modelIdx >= 0 ? modelIdx : 1;
      const vi = vgIdx >= 0 ? vgIdx : 4;
      for (const r of rows) {
        if (r === header) continue;
        const cells = r.querySelectorAll('td,th');
        if (!cells.length || pimIdx >= cells.length) continue;
        if (norm(cells[pimIdx].textContent) === String(pim)) {
          r.setAttribute('data-roap-target', '1');
          return { ok: true,
                   model: norm(cells[mi] && cells[mi].textContent),
                   variantGroup: norm(cells[vi] && cells[vi].textContent),
                   mlp: norm(cells[mlpIdx] && cells[mlpIdx].textContent), mlpIdx };
        }
      }
    }
    return { ok: false };
  }, pim);
  let res = await scan();
  for (let i = 0; i < 15 && !res.ok; i++) {
    await page.mouse.wheel(0, 4000);
    await page.waitForTimeout(500);
    res = await scan();
  }
  return res;
}

Given('I load the Driveaway Price test data', async function () {
  _ensureDriveawayData(this);
  const row = (this.driveawayPriceData || [])[0] || {};
  assert.ok(Object.keys(row).length, 'No "Driveaway Price - Test Data" row found in Confluence.');
  console.log(`📋 Driveaway test data: Pim=${row.Pim ?? row.PIM ?? row.pim}, postcode=${row.postcode}, CPC=${row['CPC URL']}`);
});

// Resolve an environment-specific page URL from world.pageUrls, which world.js
// populates from the Confluence "Environment Configuration" URL table keyed by
// the `Page` column (lower-cased). So a `Page = ROAP` row's URL for the active
// environment is available here as pageUrls['roap']. Tries each key in order.
function _envPageUrl(world, ...keys) {
  const pageUrls = world.pageUrls || {};
  for (const k of keys) {
    const v = (pageUrls[k] ?? pageUrls[String(k).toLowerCase()] ?? '').toString().trim();
    if (/^https?:\/\//i.test(v)) return v.replace(/\/+$/, '');
  }
  return '';
}

Given('I open the ROAP URL from test data', async function () {
  _ensureDriveawayData(this);
  const row = (this.driveawayPriceData || [])[0] || {};
  // Prefer the active-environment ROAP URL (Page=ROAP row in the Confluence
  // Environment Configuration), falling back to a roap_url column on the
  // Driveaway Price sheet if the environment table has no ROAP entry.
  const target = _envPageUrl(this, 'roap', 'ROAP')
    || (row.roap_url || row['ROAP URL'] || row.ROAP_URL || '').toString().trim();
  assert.ok(/^https?:\/\//i.test(target),
    `ROAP URL is not a valid http(s) URL: "${target}". Add a "Page = ROAP" row to the Environment Configuration table (or a roap_url column to "Driveaway Price - Test Data").`);
  _setupNetworkIntercept(this);
  console.log(`📋 Opening ROAP [env: ${this.environmentName || 'unknown'}]: ${target}`);
  await this.page.goto(target, { waitUntil: 'domcontentloaded', timeout: 60000 });
  await this.page.waitForLoadState('networkidle', { timeout: 20000 }).catch(() => {});
  await this.page.waitForTimeout(1500);
});

When('I login using the username and password from test data', async function () {
  // Credentials come from .env (ROAP_USERNAME/ROAP_PASSWORD) — never committed
  // to git via localTestData.js. The sheet fields remain as a fallback for any
  // non-secret override.
  _ensureDriveawayData(this);
  const row = (this.driveawayPriceData || [])[0] || {};
  const username = (process.env.ROAP_USERNAME || row.username || row.Username || row.email || row.Email || '').toString().trim();
  const password = (process.env.ROAP_PASSWORD || row.password || row.Password || row.pass || '').toString().trim();
  assert.ok(username && password, 'ROAP_USERNAME / ROAP_PASSWORD must be set in .env');
  await _fillRoapCredentials(this.page, username, password);
  const btn = this.page.getByRole('button', { name: /log ?in|sign ?in|submit/i }).first();
  if (await btn.count()) await btn.click().catch(() => {});
  else await this.page.locator('button[type="submit"], input[type="submit"]').first().click().catch(() => {});
  await this.page.waitForLoadState('networkidle', { timeout: 25000 }).catch(() => {});
  await this.page.waitForTimeout(3000);
  const ok = await this.page.getByText(/Offers/i).first().isVisible().catch(() => false);
  console.log(`📋 ROAP login ${ok ? 'succeeded — Offers page visible' : 'submitted (Offers not confirmed)'}`);
});

// Accepts both the new "Pim" wording and the legacy "FCAI" wording so the step
// keeps matching whether the Confluence feature file has been updated yet.
When(/^I retrieve the (?:Pim(?: value)?|FCAI) from test data$/i, async function () {
  _ensureDriveawayData(this);
  const row = (this.driveawayPriceData || [])[0] || {};
  // Prefer the new Pim column; fall back to FCAI during the transition.
  this.pim = (row.Pim ?? row.PIM ?? row.pim ?? row.FCAI ?? row.fcai ?? '').toString().trim();
  assert.ok(this.pim, 'No Pim value in "Driveaway Price - Test Data".');
  console.log(`📋 Pim = ${this.pim}`);
});

When(/^I search the vehicle using (?:Pim(?: value)?|FCAI)$/i, async function () {
  assert.ok(this.pim, 'Pim not set — the retrieve step must run first.');
  await this.page.waitForLoadState('networkidle', { timeout: 15000 }).catch(() => {});
  const found = await _tagRoapPimRow(this.page, this.pim);
  assert.ok(found.ok, `Could not find a row with Pim=${this.pim} in the ROAP Offers table.`);
  this.roapModel = found.model;
  this.roapMlpIdx = found.mlpIdx;
  console.log(`🔎 Found ROAP row: ${found.model} / ${found.variantGroup} (Pim ${this.pim}, MLP ${found.mlp})`);
});

When('I capture the MLP from ROAP', async function () {
  const row = this.page.locator('[data-roap-target="1"]').first();
  assert.ok(await row.count(), 'Pim row not tagged — the search step must run first.');
  // Use the MLP column index resolved from the header during the search step
  // (falls back to 9) so it stays correct if the FCAI column is removed.
  const mlpIdx = Number.isInteger(this.roapMlpIdx) && this.roapMlpIdx >= 0 ? this.roapMlpIdx : 9;
  const mlpText = await this.page.evaluate((idx) => {
    const r = document.querySelector('[data-roap-target="1"]');
    const cells = r ? r.querySelectorAll('td,th') : [];
    return cells[idx] ? cells[idx].textContent.replace(/\s+/g, ' ').trim() : '';
  }, mlpIdx);
  const mlp = _toNum(mlpText);
  assert.ok(Number.isFinite(mlp) && mlp > 0, `Could not read a numeric MLP (got "${mlpText}").`);
  this.roapMlp = mlp;
  this.roapMlpText = mlpText;
  console.log(`📌 ROAP MLP = ${mlpText} (${mlp})`);
});

When('I capture the Driveaway Price from ROAP', async function () {
  // Expand the tagged row's package sub-row. Prefer a checkbox inside the row;
  // fall back to a #selected--<pim> checkbox, then to clicking the row itself.
  const targetRow = this.page.locator('[data-roap-target="1"]').first();
  const rowCb = targetRow.locator('input[type="checkbox"]').first();
  if (await rowCb.count()) {
    if (!(await rowCb.isChecked().catch(() => false))) await rowCb.click({ force: true }).catch(() => {});
  } else {
    const cb = this.page.locator(`#selected--${this.pim}`).first();
    if (await cb.count()) {
      if (!(await cb.isChecked().catch(() => false))) await cb.click({ force: true }).catch(() => {});
    } else {
      await targetRow.click().catch(() => {});
    }
  }
  await this.page.waitForTimeout(1500);
  // Scope the search to the sibling rows immediately after the tagged Pim row
  // (the expanded Driveaway sub-row) so we don't read another vehicle's offer.
  const info = await this.page.evaluate(() => {
    const norm = s => (s || '').replace(/\s+/g, ' ').trim();
    const re = /drive\s*-?\s*away[^$]*\$\s*([\d,]+(?:\.\d{1,2})?)/i;
    const target = document.querySelector('[data-roap-target="1"]');
    if (!target) return { err: 'no tagged row' };
    const found = [];
    let el = target.nextElementSibling, steps = 0;
    while (el && steps < 6) {
      const t = norm(el.textContent);
      const m = t.match(re);
      if (m) found.push({ text: t.slice(0, 160), amount: m[1] });
      el = el.nextElementSibling; steps++;
    }
    return { found };
  });
  // A missing tagged row IS a real failure — the search step never ran or the
  // Pim row vanished — so keep asserting on that.
  assert.ok(!info.err, `Pim row not tagged (${info.err}) — the "search the vehicle using Pim value" step must run first.`);
  const found = info.found || [];
  console.log(`📋 Driveaway sub-row candidates: ${JSON.stringify(found)}`);
  const da = found.length ? _toNum(found[0].amount) : NaN;
  if (!found.length || !(Number.isFinite(da) && da > 0)) {
    // No driveaway offer configured against this Pim. Record it and carry on so
    // the MLP comparison still runs; the driveaway check reports the note.
    this.roapDriveaway = null;
    this.roapDriveawayText = 'Not available';
    this.roapDriveawayUnavailable = true;
    const why = found.length ? ` (unreadable amount in "${found[0].text}")` : '';
    console.log(`⚠️  Driveaway price is not available for this model (${_driveawayModelLabel(this)}) in ROAP${why}`);
  } else {
    this.roapDriveaway = da;
    this.roapDriveawayText = `$${found[0].amount}`;
    console.log(`📌 ROAP Driveaway = $${found[0].amount} (${da})`);
  }
  // Save ONE ROAP evidence screenshot showing the Pim row + expanded driveaway.
  // Named with the Pim value so the report's auxiliary-screenshot scan (which
  // dedupes by the name key) only ever surfaces this single "Pim<n>" image.
  // Scroll the Pim row into view and capture the VIEWPORT (not fullPage) so the
  // shot actually shows the Pim row — a full-page shot of the 291-row table
  // would only show the top of the list, not the Pim vehicle.
  try {
    const dir = 'screenshots'; if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    const ts = new Date().toISOString().replace(/[:.]/g, '-');
    const file = path.join(dir, `roap-Driveaway-Pim${this.pim}-${ts}.png`);
    const targetRow = this.page.locator('[data-roap-target="1"]').first();
    await targetRow.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => {});
    // Nudge up a little so the row sits below the sticky header, with its
    // expanded driveaway sub-row visible underneath.
    await this.page.evaluate(() => window.scrollBy(0, -120)).catch(() => {});
    await this.page.waitForTimeout(400);
    const buf = await this.page.screenshot({ fullPage: false });
    fs.writeFileSync(file, buf);
    if (typeof this.attach === 'function') this.attach(buf, 'image/png');
    this.roapScreenshotPath = file;
  } catch { /* ignore */ }
});

// Resolve the calculator (CPC) base URL for the ACTIVE environment. world.js
// populates `this.pageUrls` from the Confluence "Environment Configuration"
// table (Status=Yes) / activeEnvironment.json cache, so the same scenario runs
// against Stage / Prod / Dev with no code change — the same mechanism the
// calculator_pricing feature uses. Falls back to the hyundai site root, then
// to production.
function _calculatorBaseUrl(world) {
  const direct = _envPageUrl(world, 'calculator', 'Calculator');
  if (direct) return direct;
  const pageUrls = world.pageUrls || {};
  for (const u of Object.values(pageUrls)) {
    try {
      const url = new URL(u);
      if (/hyundai/i.test(url.hostname)) return `${url.protocol}//${url.host}/au/en/shop/calculator`;
    } catch { /* ignore */ }
  }
  return 'https://www.hyundai.com/au/en/shop/calculator';
}

// Turn a ROAP model name into the calculator URL slug:
//   "VENUE"         -> "venue"
//   "SANTA FE"      -> "santa-fe"
//   "KONA Electric" -> "kona-electric"
// Drops "(QX)"-style qualifiers and collapses any punctuation to single hyphens.
function _modelSlug(name) {
  return String(name || '')
    .replace(/\(.*?\)/g, ' ')        // drop parenthetical qualifiers
    .replace(/[^a-zA-Z0-9]+/g, ' ')  // punctuation -> space
    .trim()
    .toLowerCase()
    .replace(/\s+/g, '-');           // spaces -> hyphens
}

// Slugs to try, longest first: "KONA Electric" -> ["kona-electric", "kona"].
// ROAP's Model column is usually already the calculator model ("KONA (SX2)" ->
// "kona"), but a test-data Site_Model / model_slug column often carries the
// VARIANT GROUP instead ("KONA Electric") — and on the calculator that is an
// energy type inside /calculator/kona, not a model of its own. Trimming trailing
// words recovers the real model page.
function _slugCandidates(name) {
  const base = _modelSlug(name);
  if (!base) return [];
  const parts = base.split('-');
  const out = [];
  for (let n = parts.length; n >= 1; n--) out.push(parts.slice(0, n).join('-'));
  return out;
}

// Did we land on a MODEL calculator page, or on the model-picker landing page?
// The calculator is a SPA: /au/en/shop/calculator/<anything> returns HTTP 200
// and resolves the model client-side, so an HTTP status probe cannot tell the
// two apart (verified on dev: /calculator/kona-electric -> 200, renders the
// picker). The only trustworthy signal is rendered UI — the option-group
// headings, or the "Change vehicle" control. Mirrors CPC-pageLoad.steps.js, and
// deliberately does NOT key on "Coming soon", which is a site-wide promo block.
async function _cpcModelPageLoaded(page, timeoutMs = 25000) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const ok = await page.evaluate(() => {
      const headings = Array.from(document.querySelectorAll('h1,h2,h3,h4'))
        .filter(el => el.offsetParent !== null)
        .map(el => (el.innerText || '').trim());
      if (headings.some(t => /^(select energy type|body type|select variant|choose your powertrain|transmission)\.?$/i.test(t))) return true;
      return /change vehicle/i.test(document.body.innerText || '');
    }).catch(() => false);
    if (ok) return true;
    await page.waitForTimeout(500);
  }
  return false;
}

When('I open the CPC URL from test data', async function () {
  _ensureDriveawayData(this);
  const row = (this.driveawayPriceData || [])[0] || {};

  // Build the calculator URL at run time from the active environment's
  // calculator base + the model captured from ROAP (set by the
  // "I search the vehicle using Pim value" step). An explicit slug column in the
  // sheet, if present, overrides the auto-derived slug.
  const base = _calculatorBaseUrl(this);
  const explicitSlug = (row.Site_Model || row.site_model || row.model_slug
    || row.calculator_slug || row.Slug || row.slug || '').toString().trim();

  // Try the test-data slug first, then the model captured from ROAP, each
  // trimmed word-by-word, then any explicit 'CPC URL' column as a last resort.
  const slugs = [];
  for (const s of [..._slugCandidates(explicitSlug), ..._slugCandidates(this.roapModel)]) {
    if (s && !slugs.includes(s)) slugs.push(s);
  }
  assert.ok(slugs.length,
    `Could not derive a calculator model slug (ROAP model = "${this.roapModel || ''}"). ` +
    `Ensure the Pim search step ran, or add a model_slug column to "Driveaway Price - Test Data".`);

  const fallbackUrl = (row['CPC URL'] || row.CPCURL || row.cpc_url || row.cpcUrl || '').toString().trim();
  const attempts = slugs.map(s => `${base}/${s}`);
  if (/^https?:\/\//i.test(fallbackUrl) && !attempts.includes(fallbackUrl)) attempts.push(fallbackUrl);

  // Capture every variantpricecalculator response. It fires per variant/option
  // selection and carries pimId + mlp/mlpFromPIM + finalDriveAwayPrice, so we
  // index the parsed records by pimId to match the test-data Pim later.
  this._cpcByPim = {};
  this._cpcRawByPim = {};
  this._cpcVpcUrlByPim = {};
  this._cpcLatest = null;
  if (!this._cpcVpcListener) {
    this.page.on('response', async (resp) => {
      try {
        if (!/variantpricecalc/i.test(resp.url()) || !resp.ok()) return;
        const body = await resp.text().catch(() => '');
        const json = body ? JSON.parse(body) : null;
        if (!json) return;
        const rec = _extractPimRecord(json);
        this._cpcLatest = rec;
        // Sibling variants first, then the selected one — so the authoritative
        // record wins if the payload describes the same pimId twice.
        for (const sib of _extractOwnPimRecords(json)) {
          if (this._cpcByPim[sib.pimId]) continue;
          this._cpcByPim[sib.pimId] = sib;
          this._cpcRawByPim[sib.pimId] = body;
          this._cpcVpcUrlByPim[sib.pimId] = resp.url();
        }
        if (rec.pimId != null) {
          this._cpcByPim[rec.pimId] = rec;
          this._cpcRawByPim[rec.pimId] = body;
          this._cpcVpcUrlByPim[rec.pimId] = resp.url();
        }
      } catch { /* ignore */ }
    });
    this._cpcVpcListener = true;
  }

  // Record the suburb/postcode lookup the location modal calls. When it comes
  // back empty the modal can't set a dealer, and the calculator bounces to its
  // landing page — knowing the count turns that into a one-line diagnosis
  // instead of a mystery "wrong page" failure.
  if (!this._cpcLocationListener) {
    this.page.on('response', async (resp) => {
      try {
        if (!/\/common\/v\d+\/location\?/i.test(resp.url())) return;
        const body = await resp.text().catch(() => '');
        let count = null;
        try { const j = JSON.parse(body); if (Array.isArray(j)) count = j.length; } catch { /* ignore */ }
        this._lastLocationApi = { url: resp.url(), status: resp.status(), count };
      } catch { /* ignore */ }
    });
    this._cpcLocationListener = true;
  }

  console.log(`📋 Environment calculator base: ${base}`);
  console.log(`📋 ROAP model "${this.roapModel || ''}"${explicitSlug ? ` / test-data slug "${explicitSlug}"` : ''} → candidates: ${slugs.join(', ')}`);

  // The calculator renders NOTHING until a dealer is set — verified on prod:
  // /calculator/kona shows no option groups at all before the location modal is
  // answered. So the "is this really a model page?" check can't happen here; the
  // dealer step below walks these candidates and validates each after setting the
  // dealer. Just open the first one.
  this._cpcAttempts = attempts;
  console.log(`📋 Opening CPC: ${attempts[0]}`);
  await this.page.goto(attempts[0], { waitUntil: 'domcontentloaded', timeout: 60000 });
});

// 6 min: this step may answer the location modal and wait for the calculator to
// render once per candidate URL before one of them proves out.
When('I set the dealer using the postcode and suburb from test data', { timeout: 6 * 60 * 1000 }, async function () {
  _ensureDriveawayData(this);
  const row = (this.driveawayPriceData || [])[0] || {};
  const postcode = (row.postcode || row.Postcode || '2000').toString().trim();

  // Setting the dealer is also what proves we're on a real model page: the
  // calculator only renders its option groups once a dealer exists. So each
  // candidate URL from the previous step is answered here and then checked —
  // /calculator/kona-electric returns HTTP 200 and keeps its URL but never
  // renders a calculator, which is exactly how a bad slug used to slip through
  // and leave the run sitting on the model-picker page.
  const attempts = (this._cpcAttempts && this._cpcAttempts.length)
    ? this._cpcAttempts : [this.page.url()];
  let target = null;
  const rejected = [];
  for (const url of attempts) {
    if (this.page.url() !== url) {
      console.log(`📋 Opening CPC: ${url}`);
      const navOk = await this.page.goto(url, { waitUntil: 'domcontentloaded', timeout: 60000 })
        .then(() => true).catch(e => { console.warn(`⚠️  Navigation failed: ${e.message}`); return false; });
      if (!navOk) { rejected.push(url); continue; }
    }
    // Clear per attempt, so whatever a rejected candidate priced is dropped and
    // the winning attempt's captures survive into the lookup step.
    this._cpcByPim = {};
    this._cpcRawByPim = {};
    this._cpcVpcUrlByPim = {};
    this._cpcLatest = null;
    console.log(`📍 Setting dealer via postcode ${postcode} on ${url}`);
    await handleLocationModal(this.page, postcode);
    if (await _cpcModelPageLoaded(this.page)) { target = url; break; }
    rejected.push(url);
    console.warn(`⚠️  ${url} — no calculator UI after setting the dealer (landed on ${this.page.url()}) — trying the next candidate`);
  }

  if (!target) {
    // Distinguish "the slug is wrong" from "this environment can't resolve a
    // dealer at all" — on Dev the suburb/postcode API answers 200 with [] for
    // every query, so no postcode can ever set a dealer and the calculator
    // redirects to its landing page. That is an environment data problem, and
    // saying so beats reporting it as a missing pimId three steps later.
    const loc = this._lastLocationApi;
    const locNote = loc
      ? (loc.count === 0
          ? `\nThe location lookup (${loc.url}) returned HTTP ${loc.status} with 0 suburbs, so NO dealer can be set on this environment — postcode "${postcode}" is not the problem. Check the suburb/postcode data is published here, or run against an environment where it is.`
          : `\nLocation lookup returned ${loc.count} suburb(s) — the dealer data is fine, so the model slug is the likely problem.`)
      : '\nNo location lookup response was seen at all.';
    assert.fail(
      `CPC calculator never rendered for postcode "${postcode}". Tried:\n  - ${rejected.join('\n  - ')}` +
      `\nROAP model = "${this.roapModel || ''}". Currently on ${this.page.url()}.${locNote}`);
  }
  console.log(`✅ CPC model calculator open: ${target}`);

  // Wait for the first variantpricecalculator response (fires once the dealer is
  // set and the default variant prices).
  for (let i = 0; i < 30 && !this._cpcLatest; i++) await this.page.waitForTimeout(500);
  assert.ok(this._cpcLatest,
    'No variantpricecalculator response was captured after setting the dealer.');
  console.log(`📋 Captured CPC pricing API — default variant pimId=${this._cpcLatest.pimId}`);
});

// 25 min: the sweep can run two full passes (~4-7 min each on a model with as
// many combinations as KONA) and must not be cut off mid-walk — a truncated walk
// reports "not found" for a variant that simply hadn't been reached yet.
When(/^I locate the vehicle whose (?:Pim value matches|serviceId equals the FCAI)$/i, { timeout: 25 * 60 * 1000 }, async function () {
  assert.ok(this.pim, 'Pim not set.');
  const want = String(this.pim).trim();
  this._cpcByPim = this._cpcByPim || {};
  // Exact match first, then a leading-zero/whitespace-tolerant one, so a
  // test-data "0920" still matches a CPC "920".
  const normPim = (s) => String(s == null ? '' : s).trim().replace(/^0+(?=\d)/, '');
  const matched = () => {
    if (this._cpcByPim[want]) return this._cpcByPim[want];
    const w = normPim(want);
    for (const [k, r] of Object.entries(this._cpcByPim)) if (normPim(k) === w) return r;
    return null;
  };

  // The default variant already fired a variantpricecalculator on load. If it
  // isn't the target, walk every option combination — each selection fires a
  // fresh variantpricecalculator — and stop as soon as the matching pimId lands.
  // Two passes with opposite group orderings. Which group constrains which
  // differs by model (on KONA Electric the N Line pack limits the powertrain;
  // elsewhere it can be the reverse), and a group is only enumerated under the
  // state its ancestors left behind — so one ordering can never reach every
  // combination on every model. The second pass only runs if the first missed.
  let walk = { found: false, aborted: false, clicks: 0 };
  for (const packsFirst of [true, false]) {
    if (matched()) break;
    console.log(`🔎 Searching calculator combinations for pimId=${want} (packs ${packsFirst ? 'before' : 'after'} powertrain) …`);
    const pass = await _cpcSelectAllCombosUntil(this.page, async () => !!matched(), { packsFirst })
      .catch(err => { console.warn(`⚠️  CPC combination walk error: ${err.message}`); return { found: false, aborted: true, clicks: 0 }; });
    walk = { found: pass.found, aborted: walk.aborted || pass.aborted, clicks: walk.clicks + pass.clicks };
    console.log(`🔎 Pass finished after ${pass.clicks} selection(s) — ${Object.keys(this._cpcByPim).length} distinct pimId(s) seen so far`);
    if (pass.found || pass.aborted) break;
  }

  const rec = matched();
  if (!rec) {
    const all = Object.entries(this._cpcByPim).map(([pid, r]) =>
      `pimId=${pid} (${r.description || r.variantId || '?'}) MLP=${r.mlp} DriveAway=${r.driveaway}`);
    // Say plainly whether the sweep actually completed — an aborted walk means
    // "not found yet", not "this variant doesn't exist on the calculator".
    const how = walk.aborted
      ? `the combination walk ABORTED early after ${walk.clicks} selection(s) (page closed or click cap reached), so not every combination was tried`
      : `every combination was selected (${walk.clicks} selection(s))`;
    assert.fail(
      `No CPC variant with pimId=${want} — ${how}. ` +
      `Seen ${all.length} pimId(s):\n  - ${all.join('\n  - ') || '(none — no variantpricecalculator responses captured)'}`
    );
  }

  this.cpcPrice = _toNum(rec.mlp);
  this.cpcPriceEstimate = _toNum(rec.driveaway);
  // The calculator can return a variant with no driveaway estimate at all —
  // flag it rather than letting the comparison fail on a NaN.
  if (!(Number.isFinite(this.cpcPriceEstimate) && this.cpcPriceEstimate > 0)) {
    this.cpcPriceEstimate = null;
    this.cpcDriveawayUnavailable = true;
    console.log(`⚠️  CPC returned no driveaway estimate for pimId ${want}`);
  }
  console.log(`📌 CPC pimId ${want}: MLP(price)=${this.cpcPrice}, DriveAway(priceEstimate)=${this.cpcPriceEstimate ?? 'not available'}${rec.description ? ` [${rec.description}]` : ''}`);

  // Surface the matched variantpricecalculator response in the report's API
  // Payload panel. The `source` includes "verification" so world.js's
  // findFormSubmissionCall picks THIS call over any tracking XHRs.
  if (Array.isArray(this._capturedApiPayloads)) {
    this._capturedApiPayloads.push({
      url: (this._cpcVpcUrlByPim && this._cpcVpcUrlByPim[want]) || 'variantpricecalculator',
      method: 'GET',
      requestBody: '',
      requestHeaders: {},
      statusCode: 200,
      responseHeaders: { 'content-type': 'application/json' },
      responseBody: (this._cpcRawByPim && this._cpcRawByPim[want]) || JSON.stringify(rec, null, 2),
      timestamp: new Date().toISOString(),
      source: 'roap-variantpricecalculator-verification',
    });
    console.log(`📎 variantpricecalculator payload (pimId ${want}) captured for the report`);
  }
});

// Confirmed mapping: ROAP MLP  ==  CPC `mlpFromPIM` (falling back to `mlp`),
// which is what _extractPimRecord puts in rec.mlp -> this.cpcPrice.
// The legacy "priceEstimate" wording is still accepted so the step keeps
// matching a Confluence feature that hasn't been re-worded yet — but it was
// always a misnomer: priceEstimate is a driveaway field, not an MLP one.
Then(/^I verify the CPC (?:mlpFromPIM|priceEstimate) matches the ROAP MLP$/i, async function () {
  assert.ok(Number.isFinite(this.roapMlp), 'ROAP MLP not captured.');
  assert.ok(Number.isFinite(this.cpcPrice), 'CPC mlpFromPIM not captured.');
  const diff = Math.abs(this.roapMlp - this.cpcPrice);
  console.log(`🔍 MLP check — ROAP MLP=$${this.roapMlp} vs CPC mlpFromPIM=$${this.cpcPrice} (diff ${diff.toFixed(2)})`);
  assert.ok(diff <= 1, `MLP mismatch: ROAP MLP $${this.roapMlp} != CPC mlpFromPIM $${this.cpcPrice}`);
  // Remembered so the driveaway step can say "MLP is matching" in its note when
  // this model has no driveaway offer to compare.
  this.mlpMatched = true;
  console.log('✅ MLP matches');
});

// Confirmed mapping: ROAP Driveaway  ==  CPC `finalDriveAwayPrice` (falling back
// to `priceEstimate`), which _extractPimRecord puts in rec.driveaway ->
// this.cpcPriceEstimate. The world property keeps its legacy name; the field it
// actually holds is finalDriveAwayPrice.
// The older "Estimated Drive Away price" wording is still accepted so the step
// keeps matching a Confluence feature that hasn't been re-worded yet.
Then(/^I verify the CPC (?:finalDriveAwayPrice|Estimated Drive Away price) matches the ROAP Driveaway Price$/i, async function () {
  const label = _driveawayModelLabel(this);
  const roapMissing = !Number.isFinite(this.roapDriveaway);
  const cpcMissing = !Number.isFinite(this.cpcPriceEstimate);

  // The scenario only passes when BOTH prices verify. A model with no ROAP
  // driveaway offer therefore fails — but with the plain-English reason rather
  // than a selector-level error. The CPC estimate is deliberately not quoted:
  // there is nothing on the ROAP side to compare it against.
  if (roapMissing) {
    const note = `Driveaway price is not available for this model (${label})`
      + (this.mlpMatched ? ', but the MLP is matching.' : '.');
    _setScenarioNote(this, note);
    assert.fail(note);
  }

  // ROAP publishes a driveaway offer that the calculator doesn't show — that IS
  // an inconsistency worth failing on.
  if (cpcMissing) {
    const note = `Driveaway price is not available for this model (${label}) on the calculator, but ROAP has a driveaway offer of $${this.roapDriveaway.toLocaleString()}.`;
    _setScenarioNote(this, note);
    assert.fail(note);
  }

  const diff = Math.abs(this.roapDriveaway - this.cpcPriceEstimate);
  console.log(`🔍 Driveaway check — ROAP Driveaway=$${this.roapDriveaway} vs CPC finalDriveAwayPrice=$${this.cpcPriceEstimate} (diff ${diff.toFixed(2)})`);
  assert.ok(diff <= 1, `Driveaway mismatch: ROAP Driveaway $${this.roapDriveaway} != CPC finalDriveAwayPrice $${this.cpcPriceEstimate}`);
  console.log('✅ Driveaway matches');
});
