/**
 * Auto-Generated Step Definitions for: Hyundai homepage Contact Us flow
 * Source: test.feature
 * Generated: 2026-04-29T03:50:13.635Z
 * Target URL: https://stage.hyundai.com.au/au/en
 *
 * DOM Field Map:
 *   (no DOM map available â€” using autoHeal fallbacks)
 *
 * These steps were auto-generated by the Confluence Test Agent because no
 * matching step definitions were found. Each step uses Playwright for real
 * browser interactions and assertions.
 */
import { Given, When, Then } from '@cucumber/cucumber';
import { strict as assert } from 'node:assert';

Given('the user has loaded the test data from the Confluence page', async function () {
  // Test data is loaded in the Before hook from Confluence
  assert.ok(this.allConfluenceData || (this.testData && this.testData.length > 0),
    'Test data should be loaded from Confluence');
});

// 'the user is on the Hyundai Home page' is handled by the generic
// `Given(/^the user is on the (.+?) page$/i, ...)` step in common_steps.js —
// removed here to avoid an ambiguous-step-definition clash.

When('the user clicks on Contact us in footer', async function () {
  // Auto-heal: tries button text, role=button, input[type=submit], link, aria-label fallbacks (scoped to <footer>)
  await this.clickButton('Contact us', { section: 'footer' });
  await this.page.waitForTimeout(2000);
});

// 'the Customer Care page is displayed' and 'the Contact Us page is
// displayed' are now handled by the generic
// Then(/^the (.+?) page (?:should be|is) displayed$/, ...) step in
// common_steps.js (identical slug/heading/title check) — the two duplicate
// blocks below are removed to avoid an ambiguous-step-definition clash.
/* removed-duplicate
Then('the Customer Care page is displayed', async function () {
  await this.page.waitForLoadState('domcontentloaded');
  await this.page.waitForTimeout(1500);
  const _pageName = "Customer Care";
  const _curUrl = this.page.url();
  let _ok = (await this.page.content()).length > 500;
  // If we know the page name, verify the URL contains a slug derived from it
  // OR the page heading/title contains the name.
  if (_ok && _pageName) {
    const _slug = _pageName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    const _firstWord = _pageName.toLowerCase().split(/\s+/)[0];
    const _urlOk = _curUrl.toLowerCase().includes(_slug) || _curUrl.toLowerCase().includes(_firstWord);
    if (!_urlOk) {
      // URL doesn't match â€” fall back to checking visible heading text
      const _re = new RegExp(_pageName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i');
      const _headingMatch = await this.page.locator('h1, h2').filter({ hasText: _re }).first().isVisible().catch(() => false);
      const _titleMatch = _re.test(await this.page.title().catch(() => ''));
      _ok = _headingMatch || _titleMatch;
      if (!_ok) console.warn(`âš ï¸  Page "${_pageName}" expected â€” current URL is ${_curUrl}`);
    }
  }
  assert.ok(_ok, `Page "${_pageName || 'expected'}" should be displayed (current URL: ${_curUrl})`);
});
*/

When('the user clicks on Contact us', async function () {
  // Auto-heal: tries button text, role=button, input[type=submit], link, aria-label fallbacks
  await this.clickButton('Contact us');
  await this.page.waitForTimeout(2000);
});

/* removed-duplicate
Then('the Contact Us page is displayed', async function () {
  await this.page.waitForLoadState('domcontentloaded');
  await this.page.waitForTimeout(1500);
  const _pageName = "Contact Us";
  const _curUrl = this.page.url();
  let _ok = (await this.page.content()).length > 500;
  // If we know the page name, verify the URL contains a slug derived from it
  // OR the page heading/title contains the name.
  if (_ok && _pageName) {
    const _slug = _pageName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    const _firstWord = _pageName.toLowerCase().split(/\s+/)[0];
    const _urlOk = _curUrl.toLowerCase().includes(_slug) || _curUrl.toLowerCase().includes(_firstWord);
    if (!_urlOk) {
      // URL doesn't match â€” fall back to checking visible heading text
      const _re = new RegExp(_pageName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i');
      const _headingMatch = await this.page.locator('h1, h2').filter({ hasText: _re }).first().isVisible().catch(() => false);
      const _titleMatch = _re.test(await this.page.title().catch(() => ''));
      _ok = _headingMatch || _titleMatch;
      if (!_ok) console.warn(`âš ï¸  Page "${_pageName}" expected â€” current URL is ${_curUrl}`);
    }
  }
  assert.ok(_ok, `Page "${_pageName || 'expected'}" should be displayed (current URL: ${_curUrl})`);
});
*/

// â”€â”€ Auto-appended steps â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

// NOTE: Generic steps for "opens the X website", "navigates to the X menu",
// "clicks the X submenu", and "the X page should be displayed" have been
